### ISSUE TITLE
Update 2.1.1 homebridge Problem

### ISSUE THREAD

**Issue by Lling** [mdaskalov/homebridge-dreambox#38]
Today i've updated to the new version (2.1.1)
But after a homebridge restart, a error message was in the logfile.

ERROR LOADING PLUGIN homebridge-dreambox:
[1/22/2022, 1:58:38 PM] Error [ERR_REQUIRE_ESM]: require() of ES Module /homebridge/node_modules/homebridge-dreambox/node_modules/node-fetch/src/index.js from /homebridge/node_modules/homebridge-dreambox/dist/dreambox.js not supported.
Instead change the require of index.js in /homebridge/node_modules/homebridge-dreambox/dist/dreambox.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/homebridge/node_modules/homebridge-dreambox/dist/dreambox.js:10:38)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-dreambox/dist/platform.js:7:20)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-dreambox/dist/index.js:3:20)
    at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:135:108)
    at PluginManager.initializeInstalledPlugins (/usr/local/lib/node_modules/homebridge/lib/pluginManager.js:64:30)
    at Server.start (/usr/local/lib/node_modules/homebridge/lib/server.js:106:34)
    
   
After a rollback to 2.1.0 everything was finde

**Comment by mdaskalov** [comment]
Sorry, I know 😢 
It was Dependabot automated update because of vulnerability in node-fetch which rendered the plugin unusable.

I will fix this soon, please use the old version.

**Comment by Lling** [comment]
After the [new update](https://github.com/mdaskalov/homebridge-dreambox/releases/tag/v2.1.2), everything is fine

**Comment by mdaskalov** [comment]
It was not possible to use the latest (not vulnerable) node-fetch version with typescript but finally I found a workaround... Should work now!
